version: "3.5"
services:
  changeme:
    build:
      context: .
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.changeme.rule=Host(${HOST})"
      - "traefik.http.routers.changeme.entrypoints=websecure"
      - "traefik.http.routers.changeme.tls.certresolver=letsencrypt"
    networks:
      - jnet
networks:
  jnet:
    external:
      name: jnet
