version: "3.5"
services:
  changeme:
    build: .
    container_name: "changeme"
    ports:
      - "5001:5001" # changeme
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.changeme.rule=Host(${HOST})"
      - "traefik.http.routers.changeme.entrypoints=websecure"
      - "traefik.http.routers.changeme.tls.certresolver=letsencrypt"
    networks:
      - jnet
networks:
  jnet:
    external:
      name: jnet
