version: "3.5"
services:
  portfolio:
    build: .
    container_name: "changeme"
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(${HOST})"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
    networks:
      - jnet
networks:
  jnet:
    external:
      name: jnet
