version: "3.5"
services:
  changeme:
    build: .
    image: "changeme_${ENVIRONMENT}:${VERSION}"
    ports:
      - "${PORT}:${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.changeme_${ENVIRONMENT}.rule=Host(${HOST})"
      - "traefik.http.routers.changeme_${ENVIRONMENT}.entrypoints=websecure"
      - "traefik.http.routers.changeme_${ENVIRONMENT}.tls.certresolver=letsencrypt"
    networks:
      - jnet
networks:
  jnet:
    external:
      name: jnet
